"""update product and add reservation

Revision ID: cf6ed93a029e
Revises: 2ff79a8f0624
Create Date: 2026-09-09 17:33:26.186372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6ed93a029e'
down_revision: Union[str, Sequence[str], None] = '2ff79a8f0624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'RELEASED', 'EXPIRED', name='status'), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('total_quantity', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('available_quantity', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('price_cents', sa.Integer(), nullable=False))
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('product', 'price_cents')
    op.drop_column('product', 'available_quantity')
    op.drop_column('product', 'total_quantity')
    op.drop_table('reservation')
    # ### end Alembic commands ###
